### ISSUE TITLE
Define redirection rules

### ISSUE THREAD

**Issue by adiroiban** [twisted/twisted.github.io#13]
With the move from hosting our own Trac and managing our own VM we now need to look and see what to redirect and where to redirect.

For now, the plan is for the new twistedmatrix.com website to be hosted via this repo and use the GitHub Pages service.

The new website will only provide a very minimal set of functionalities in comparison with Trac.

As a high level the following Trac services are no longer available

* Trac Tickets -> Moved to GitHub Issue - First part done in #11 
* Trac Wiki -> Moved to a GitHub Repo
* Trac Ticket Reports -> Moved to GitHub Issue search URL
* Documentation static files /documentes/ - partly moved to Read The Docs

This ticket is about defining the exact list of URLs that need redirection and decide where to redirect.

**Comment by adiroiban** [comment]
Trac Tickets
============

We will have tickets above "1739" with a direct mapping.

Dan will help here with the mapping for the numbers for tickets below 1739


Trac Wiki
=========

We will have https://github.com/twisted/trac-wiki-archive
 

* https://twistedmatrix.com/trac/wiki/FrequentlyAskedQuestions -> https://github.com/twisted/trac-wiki-archive/FrequentlyAskedQuestions.mediawiki
* https://twistedmatrix.com/trac/wiki/ContinuousIntegration/Buildslaves/Rackspace -> https://github.com/twisted/trac-wiki-archive/ContinuousIntegration/Buildslaves/Rackspace.mediawiki
*

Trac ticket reports
===================

Are all the links from this page https://twistedmatrix.com/trac/report

From 1 to 31

We need to see how to transfer translate the reports to GitHub URLs.

The source is something like https://twistedmatrix.com/trac/report/1


Documentation static pages
==========================

We need to  create an archive repo, that is served via GitHub pages and will allow us something like this https://twistedmatrix.com/documents/14.0.1/

Starting with 21.2.0 we have everything on Read The Docs https://docs.twistedmatrix.com/en/twisted-21.2.0/

Starting with 14.0.2 we have

Special links

* https://twistedmatrix.com/documents/  -> https://docs.twistedmatrix.com/en/stable/
* https://twistedmatrix.com/documents/current/* https://docs.twistedmatrix.com/en/stable/:splat

Version info

```
2.4.0 - full archive
2.5.0 - full archive
8.0.0 - full archive
8.0.1
8.1.0
8.2.0
9.0.0
10.0.0
10.1.0
10.2.0
11.0.0
11.1.0
12.0.0
12.1.0
12.2.0
12.3.0
13.0.0
13.1.0
13.2.0
14.0.0
14.0.1
14.0.2 - https://docs.twistedmatrix.com/en/twisted-14.0.2/ and archive for API
15.0.0
15.1.0
15.2.0
15.2.1
15.3.0
15.4.0
15.5.0
16.0.0
16.1.0
16.1.1
16.2.0
16.3.0
16.3.1
16.3.2
16.4.0
16.4.1
16.5.0
16.6.0
17.1.0
17.5.0
17.9.0
18.4.0
18.7.0
18.9.0
19.10.0
19.2.0
19.2.1
19.7.0
20.3.0
21.2.0 -> https://docs.twistedmatrix.com/en/twisted-21.2.0/
```

**Comment by danuker** [comment]
Here is a JS function + Map that converts the Trac ID to a GitHub ID:

[tickets_created.txt](https://github.com/twisted/twisted.github.io/files/9010521/tickets_created.txt)

If the ID is not matched, it just copies the Trac one (which will work in most cases, except invalid links).

**Comment by adiroiban** [comment]
It looks like the documentation archive part was already implemented by myself in sept 2021

I forgot about it.
 
https://github.com/twisted/documents

for example https://twisted.org/documents/14.0.1/

**Comment by adiroiban** [comment]
Trac ticket reports
===================

Are all the links from this page https://twistedmatrix.com/trac/report

From 1 to 31

We need to see how to transfer translate the reports to GitHub URLs.

The source is something like https://twistedmatrix.com/trac/report/1


I think is best to implement this in a separate ticket
